version: '2'
services:
    web:
        container_name: todo_list_web
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./laravel:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        container_name: todo_list_app
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./laravel:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        container_name: todo_list_mysql
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"

