version: '2'
services:
    web:
        container_name: todo_list_web
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./laravel:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        container_name: todo_list_app
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./laravel:/var/www
            - ./php70.ini:/usr/local/etc/php/php.ini
        links:
            - database
        environment:
            - "DB_PORT=27017"
            - "DB_HOST=database"
    database:
        container_name: todo_list_database
        image: mongo:latest
        volumes: 
            - ./data/db:/data/db
        build:
            context: ./
            dockerfile: mongo.docker
        environment:
            - "MONGO_DATABASE=dockerApp"
        ports:
            - "27017:27017"
        command: 
            -  --rest
